### ISSUE TITLE
Newsletter signup broken - Workspaces > Public

### ISSUE THREAD

**Issue by Dangerousfish** [humanprotocol/human-app#95]
I hope this is the right repo for reporting, sincere apologies if not!

**Issue**
When a user enters their email address in the newsletter subscription form, whilst logged in to: https://app.humanprotocol.org an error is presented when they press, "subscribe"

The error presented is as follows:

"Signup is required"

![image](https://user-images.githubusercontent.com/30146283/164533017-8a2661ef-5ff0-4ef6-9916-caf3be748566.png)

**Expectation**
After populating the field with an email address and pressing subscribe, I would expect a 200 Response and an email notification to be sent to confirm that the users email address has been subscribed to the mailing list.

**Testing**
This issue is replicable in:
**_Browsers:_**
Chrome (100.0.4896.127)
Microsoft Edge (100.0.1185.44)
**_Device_**
OS: Windows 10 Pro
Resolution: 1920x1080

**Investigation**
Tracking the events around this error reveal the following:

- On pressing "Subscribe", a POST request is made to:
`POST https://api.humanprotocol.org/v1/auth/register-interest`

**This responds with a 400 - Bad Request error**

Part of this script also makes the following call and feels relevant..:
- subscribe.jsx:29

```
    if (EmailValidator.validate(email)) {
      dispatch(startGlobalLoading());
      **return sendNewsletterSignup({ email, newsletter: true })**
        .then(() => {
          setError('');
          setModalShow(true);
        })
        .catch((err) => {
          setError(err.message);
        })
```

I haven't more time to investigate at the moment and js isn't my forte, but thought it worthy of reporting.

**Comment by Dangerousfish** [comment]
Have tried this at all stages of signup:
- Before registering
- Awaiting account activation
- Active account

This issue is replicable in all states.

**Comment by vkomodey** [comment]
Hey, @Dangerousfish 

Issue has been fixed. Thank you for noting!
